name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Установить Visual Studio Build Tools
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add-to-path --quiet"

      - name: Проверить установку MSBuild
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" -version

      - name: Build with MSBuild
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" "VeterinaryClinic.sln" /p:Configuration=Debug
