name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Проверить путь к MSBuild
        run: |
          if (Test-Path "E:\Visual Studio 2022\MSBuild\Current\Bin\MSBuild.exe") {
            Write-Host "MSBuild найден!"
          } else {
            Write-Host "MSBuild не найден по пути E:\Visual Studio 2022\MSBuild\Current\Bin\MSBuild.exe"
          }

      - name: Добавить MSBuild в PATH
        run: |
          $env:PATH += ";E:\Visual Studio 2022\MSBuild\Current\Bin"
          & "E:\Visual Studio 2022\MSBuild\Current\Bin\MSBuild.exe" "VeterinaryClinic.sln" /p:Configuration=Debug