name: Lint C# Code

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint a specific project
        run: msbuild "VeterinaryClinic.csproj" /p:Configuration=Release /warnaserror

      - name: Build the solution
        run: msbuild "VeterinaryClinic.sln" /p:Configuration=Release