name: Build and Test .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Проверяем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Устанавливаем .NET Framework SDK
      - name: Set up .NET Framework
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 4.8

      # Запускаем сборку проекта
      - name: Build the project
        run: msbuild "VeterinaryClinic.sln" /p:Configuration=Release

      # Проверяем синтаксические ошибки с помощью MSBuild
      - name: Run MSBuild for syntax check
        run: msbuild "VeterinaryClinic.sln" /p:Configuration=Release /t:Restore
