name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Framework Developer Pack
        run: choco install netfx-4.7.2-devpack -y

      - name: Restore NuGet packages
        run: |
          curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o nuget.exe
          ./nuget.exe restore VeterinaryClinic.sln

      - name: Build with MSBuild (custom path)
        run: |
          & "E:\Visual Studio 2022\MSBuild\Current\Bin\MSBuild.exe" "VeterinaryClinic.sln" /p:Configuration=Debug