name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Visual Studio and .NET Framework
        run: |
          choco install visualstudio2019buildtools -y --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools"
          choco install netfx-4.7.2-devpack -y

      - name: Restore NuGet packages
        run: nuget restore VeterinaryClinic.sln

      - name: Build with MSBuild
        run: msbuild VeterinaryClinic.sln /p:Configuration=Debug