name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout исходный код
      - name: Checkout repository
        uses: actions/checkout@v2

      # Запуск сборки через MSBuild
      - name: Build the project
        run: "D:\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin\\MSBuild.exe VeterinaryClinic.sln /p:Configuration=Release"

      # Проверка восстановления пакетов и сборка
      - name: Run MSBuild for syntax check
        run: msbuild "VeterinaryClinic.sln" /p:Configuration=Release /t:Restore
