name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Загрузка установщика Visual Studio Build Tools
        run: |
          # Загружаем установщик Visual Studio Build Tools
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_installer.exe -OutFile vs_installer.exe
          # Проверяем, что файл был успешно загружен
          if (Test-Path -Path "vs_installer.exe") {
            Write-Host "Файл успешно загружен!"
          } else {
            Write-Host "Ошибка загрузки файла!"
            exit 1
          }

      - name: Установка Visual Studio Build Tools
        run: |
          # Запускаем установку
          Start-Process -FilePath vs_installer.exe -ArgumentList '--quiet', '--add-to-path', '--installProduct Microsoft.VisualStudio.2022.BuildTools' -Wait

      - name: Проверка установки MSBuild
        run: |
          # Проверяем доступность MSBuild
          & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" -version

      - name: Сборка с MSBuild
        run: |
          # Выполняем сборку проекта с использованием MSBuild
          & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" "VeterinaryClinic.sln" /p:Configuration=Debug
