name: .NET Syntax Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      - name: Run code analysis (Roslyn Analyzers)
        run: dotnet build --no-restore --configuration Release /p:RunAnalyzers=true

      - name: Run tests
        run: dotnet test --no-build --configuration Release

      - name: Publish results (Optional, if using Roslyn)
        run: dotnet publish --configuration Release