name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout исходный код
      - name: Checkout repository
        uses: actions/checkout@v2

      # Настройка MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Проверить директорию
      - name: Display current directory
        run: pwd

      # Линтинг кода с помощью StyleCop
      - name: Lint code with StyleCop
        run: dotnet build -warnaserror

      # Сборка проекта
      - name: Build the project
        run: msbuild "VeterinaryClinic.sln" /p:Configuration=Release