name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout исходный код
      - name: Checkout repository
        uses: actions/checkout@v2

      # Настройка MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Проверка структуры проекта
      - name: Validate .csproj file
        run: |
          if not exist "VeterinaryClinic.csproj" (
            echo "Error: VeterinaryClinic.csproj not found."
            exit 1
          )

      # Линтинг кода с помощью StyleCop
      - name: Lint code with StyleCop
        run: msbuild "VeterinaryClinic.sln" /p:Configuration=Release /warnaserror

      # Сборка проекта
      - name: Build the project
        run: msbuild "VeterinaryClinic.sln" /p:Configuration=Release
